export const guides = [
  {
    guideId: "G001",
    displayName: "Nimal Perera",
    baseCity: "Kandy",
    yearsExperience: 8,
    languages: ["English", "Sinhala"],
    specializations: ["Cultural", "Historical"],
    averageRating: 4.8,
    availability: "available",
    pricePerDay: 75.0,
  },
  {
    guideId: "G002",
    displayName: "Kasun Silva",
    baseCity: "Colombo",
    yearsExperience: 5,
    languages: ["English", "Tamil"],
    specializations: ["Adventure", "Wildlife"],
    averageRating: 4.5,
    availability: "busy",
    imageUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kasun",
    pricePerDay: 80.0,
  },
  {
    guideId: "G003",
    displayName: "Tharindu Fernando",
    baseCity: "Galle",
    yearsExperience: 12,
    languages: ["English", "Sinhala", "German"],
    specializations: ["Cultural", "Natural"],
    averageRating: 4.9,
    availability: "available",
    imageUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Tharindu",
    pricePerDay: 90.0,
  },
  {
    guideId: "G004",
    displayName: "Dilshan Jayasuriya",
    baseCity: "Ella",
    yearsExperience: 3,
    languages: ["English"],
    specializations: ["Hiking", "Adventure"],
    averageRating: 4.3,
    availability: "offline",
    imageUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Dilshan",
    pricePerDay: 60.0,
  },
  {
    guideId: "G005",
    displayName: "Samantha Wickramasinghe",
    baseCity: "Colombo",
    yearsExperience: 10,
    languages: ["English", "Sinhala", "French"],
    specializations: ["Historical", "Cultural"],
    averageRating: 4.7,
    availability: "available",
    imageUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Samantha",
    pricePerDay: 85.0,
  },
  {
    guideId: "G006",
    displayName: "Ruwan Senanayake",
    baseCity: "Kandy",
    yearsExperience: 6,
    languages: ["English", "Tamil"],
    specializations: ["Wildlife", "Natural"],
    averageRating: 4.4,
    availability: "busy",
    imageUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Ruwan",
    pricePerDay: 70.0,
  },
];
